# Generated by Django 3.1.1 on 2020-09-13 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0002_user_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddFriend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmn', models.BooleanField(default=False)),
                ('add', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add', to='insta.profile')),
                ('add_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_by', to='insta.profile')),
            ],
        ),
    ]
