# Generated by Django 3.1.1 on 2020-09-14 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0004_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='User_Post_commt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('you_msg', models.CharField(blank=True, max_length=250, null=True)),
                ('commt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commt', to='insta.profile')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='insta.user_post')),
            ],
        ),
    ]
