# Generated by Django 3.1.1 on 2020-09-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0005_auto_20200914_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='nopic/slide3.jpg', null=True, upload_to='media/profile_pic/'),
        ),
    ]
