# Generated by Django 3.1.1 on 2020-09-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0006_auto_20200915_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='addfriend',
            name='send_rqst',
            field=models.BooleanField(default=False),
        ),
    ]
